### ISSUE TITLE
Why do I have to reset the output path, yt-dlp path and ffmpeg path every time I reopen the software?

### ISSUE THREAD

**Issue by Memorainer** [database64128/youtube-dl-wpf#167] opened 2023-05-12 13:51 UTC
As the title indicates.Can't save the settings?

**Comment by prczsf** [comment] 2023-05-15 01:52
yes. I am facing the same issues. 
Vesion: v1.12.0.  (The v1.11.0 is OK to save the setting, and doesn't have this issue. )
OS: Win11 X64

Issues:  the setting not saved when closed the application. 
Root Cause: A file Settings.json.new was generated when application was closed, which saved all configurations. 
temp solution： manually copy the Settings.json.new to Settings.json , after application closed.

**Comment by database64128** [comment] 2023-05-15 03:23
> Settings.json.new

This is very useful information. 👍

Does this happen consistently on every run? I still can't reproduce locally. But I do have some ideas on how to fix this.

**Comment by database64128** [comment] 2023-05-15 11:45
@prczsf Thank you for the detailed reproduction steps! This has been fixed with 90f7627fbd7230d32fc47c2f978d6aa9d6f83f5a, and I'll make a quick patch release soon.

**Closed** 2023-05-15 12:41 UTC
